
version: '3.8'
services:
  gateway:
    container_name: gateway-${DENV:-dev}-${MODE:-http}
    image: europe-north1-docker.pkg.dev/xenon-height-415204/chessboxingfit/gateway-${DENV:-dev}-${MODE:-http}
    build: 
      context: ./gateway
      args:
        MODE: ${MODE:-http}
    restart: always
    ports:
      - ${PROJECT_PORT:-8080}:80
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    depends_on:
      - client
      - server
    networks:
      - node-network

  client:
    container_name: client-${DENV:-dev}
    image: europe-north1-docker.pkg.dev/xenon-height-415204/chessboxingfit/client-${DENV:-dev}
    build: 
      context: ./client
    restart: always
    networks:
      - node-network

  server:
    container_name: server-${DENV:-dev}
    image: europe-north1-docker.pkg.dev/xenon-height-415204/chessboxingfit/server-${DENV:-dev}
    build: ./server
    restart: always
    environment:
      - MONGO_URI=${MONGO_URL:-mongodb://mongodb-${DENV:-dev}:27017/db-${DENV:-dev}}
      - JWT_SECRET_KEY=${JWT_SECRET_KEY:-CXiG71NGuRfZJ8SLV76e}
      - SMTP_USER_MAIL=${SMTP_USER_MAIL:-carryitthroughlife@gmail.com}
      - SMTP_SERVICE_PASSKEY=$SMTP_SERVICE_PASSKEY
    depends_on:
      - mongodb
    networks:
      - node-network

  mongodb:
    container_name: mongodb-${DENV:-dev}
    image: mongo:6-jammy
    restart: always
    environment:
      - MONGO_INITDB_DATABASE=db-${DENV:-dev}
    volumes:
      - dbdata6:/data/db
    networks:
      - node-network

volumes:
  dbdata6:

networks:
  node-network:
    driver: bridge