
version: '3.8'
services:
  gateway:
    container_name: gateway
    build: ./gateway
    restart: always
    ports:
      - ${PROJECT_PORT:-8080}:80
    depends_on:
      - client
      - server
    networks:
      - node-network

  client:
    container_name: client
    build: 
      context: ./client
    restart: always
    networks:
      - node-network

  server:
    container_name: server
    build: ./server
    restart: always
    environment:
      - MONGO_URI=mongodb://mongodb:27017/main
      - JWT_SECRET_KEY=CXiG71NGuRfZJ8SLV76e
      - SMTP_SERVICE_PASSKEY=$SMTP_SERVICE_PASSKEY
    depends_on:
      - mongodb
    networks:
      - node-network

  mongodb:
    container_name: mongodb
    image: mongo:6-jammy
    restart: always
    environment:
      - MONGO_INITDB_DATABASE=main
    volumes:
      - dbdata6:/data/db
    networks:
      - node-network

volumes:
  dbdata6:

networks:
  node-network:
    driver: bridge